version: "3"

services:
  kernel:
    container_name: kernel
    image: merakianalytics/kernel:base
    ports:
      - 80:8080
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY}
    restart: always
    networks:
      - kernel

networks:
  kernel:
    driver: bridge
